name: Tests

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 9 * * *'

jobs:
  tests:
    name: "PHP ${{ matrix.php }}: ${{ matrix.actions.name }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2']

        actions:
          - name: PHPUnit
            run: composer test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - run: ${{ matrix.actions.run }}
